[2022-10-29 14:30:03,306] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag.fetch_file scheduled__2022-10-28T14:30:00+00:00 [queued]>
[2022-10-29 14:30:03,315] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag.fetch_file scheduled__2022-10-28T14:30:00+00:00 [queued]>
[2022-10-29 14:30:03,316] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 14:30:03,316] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-29 14:30:03,317] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 14:30:03,330] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): fetch_file> on 2022-10-28 14:30:00+00:00
[2022-10-29 14:30:03,333] {standard_task_runner.py:52} INFO - Started process 15523 to run task
[2022-10-29 14:30:03,336] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag', 'fetch_file', 'scheduled__2022-10-28T14:30:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/extract_and_load.py', '--cfg-path', '/tmp/tmpnyx6w8ig', '--error-file', '/tmp/tmpf44ereiu']
[2022-10-29 14:30:03,336] {standard_task_runner.py:80} INFO - Job 172: Subtask fetch_file
[2022-10-29 14:30:03,402] {task_command.py:369} INFO - Running <TaskInstance: dag.fetch_file scheduled__2022-10-28T14:30:00+00:00 [running]> on host cf01c04ee00d
[2022-10-29 14:30:03,483] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=fetch_file
AIRFLOW_CTX_EXECUTION_DATE=2022-10-28T14:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-28T14:30:00+00:00
[2022-10-29 14:30:05,862] {python.py:173} INFO - Done. Returned value was: None
[2022-10-29 14:30:05,877] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dag, task_id=fetch_file, execution_date=20221028T143000, start_date=20221029T143003, end_date=20221029T143005
[2022-10-29 14:30:06,001] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-29 14:30:06,042] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
